name: Deploy React Web App
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Backup deployed folder on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Backing up current app"
            which rsync || sudo apt update && sudo apt install rsync -y
            echo "Creating required directories if they don't exist"
            mkdir -p /var/www/html/harness
            timestamp=$(date +%F_%H-%M-%S)
            mkdir -p /home/ubuntu/app_backup_$timestamp
            rsync -avz /var/www/html/harness/ /home/ubuntu/app_backup_$timestamp/  
      - name: Sync source code to server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avz --delete
          path: ./
          remote_path: /home/ubuntu/docker-react/ 
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
      
      - name: Build and run Docker containers on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/docker-react
            docker compose down || true
            docker compose up --build -d
